// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package logs_test is a generated GoMock package.
package logs_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/befragment/yadro-test-applied-dev/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MocklogService is a mock of logService interface.
type MocklogService struct {
	ctrl     *gomock.Controller
	recorder *MocklogServiceMockRecorder
}

// MocklogServiceMockRecorder is the mock recorder for MocklogService.
type MocklogServiceMockRecorder struct {
	mock *MocklogService
}

// NewMocklogService creates a new mock instance.
func NewMocklogService(ctrl *gomock.Controller) *MocklogService {
	mock := &MocklogService{ctrl: ctrl}
	mock.recorder = &MocklogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklogService) EXPECT() *MocklogServiceMockRecorder {
	return m.recorder
}

// FetchLogMetadata mocks base method.
func (m *MocklogService) FetchLogMetadata(ctx context.Context, logID int) (domain.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLogMetadata", ctx, logID)
	ret0, _ := ret[0].(domain.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLogMetadata indicates an expected call of FetchLogMetadata.
func (mr *MocklogServiceMockRecorder) FetchLogMetadata(ctx, logID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLogMetadata", reflect.TypeOf((*MocklogService)(nil).FetchLogMetadata), ctx, logID)
}

// GetTopology mocks base method.
func (m *MocklogService) GetTopology(ctx context.Context, logID int) (domain.Topology, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopology", ctx, logID)
	ret0, _ := ret[0].(domain.Topology)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopology indicates an expected call of GetTopology.
func (mr *MocklogServiceMockRecorder) GetTopology(ctx, logID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopology", reflect.TypeOf((*MocklogService)(nil).GetTopology), ctx, logID)
}

// ParseLogFiles mocks base method.
func (m *MocklogService) ParseLogFiles(ctx context.Context, path string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseLogFiles", ctx, path)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseLogFiles indicates an expected call of ParseLogFiles.
func (mr *MocklogServiceMockRecorder) ParseLogFiles(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseLogFiles", reflect.TypeOf((*MocklogService)(nil).ParseLogFiles), ctx, path)
}
