// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package logs_test is a generated GoMock package.
package logs_test

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/befragment/yadro-test-applied-dev/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// Mocklogrepo is a mock of logrepo interface.
type Mocklogrepo struct {
	ctrl     *gomock.Controller
	recorder *MocklogrepoMockRecorder
}

// MocklogrepoMockRecorder is the mock recorder for Mocklogrepo.
type MocklogrepoMockRecorder struct {
	mock *Mocklogrepo
}

// NewMocklogrepo creates a new mock instance.
func NewMocklogrepo(ctrl *gomock.Controller) *Mocklogrepo {
	mock := &Mocklogrepo{ctrl: ctrl}
	mock.recorder = &MocklogrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogrepo) EXPECT() *MocklogrepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mocklogrepo) Create(ctx context.Context, log domain.Log) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocklogrepoMockRecorder) Create(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mocklogrepo)(nil).Create), ctx, log)
}

// FetchMeta mocks base method.
func (m *Mocklogrepo) FetchMeta(ctx context.Context, logID int64) (domain.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMeta", ctx, logID)
	ret0, _ := ret[0].(domain.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMeta indicates an expected call of FetchMeta.
func (mr *MocklogrepoMockRecorder) FetchMeta(ctx, logID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMeta", reflect.TypeOf((*Mocklogrepo)(nil).FetchMeta), ctx, logID)
}

// Mocknoderepo is a mock of noderepo interface.
type Mocknoderepo struct {
	ctrl     *gomock.Controller
	recorder *MocknoderepoMockRecorder
}

// MocknoderepoMockRecorder is the mock recorder for Mocknoderepo.
type MocknoderepoMockRecorder struct {
	mock *Mocknoderepo
}

// NewMocknoderepo creates a new mock instance.
func NewMocknoderepo(ctrl *gomock.Controller) *Mocknoderepo {
	mock := &Mocknoderepo{ctrl: ctrl}
	mock.recorder = &MocknoderepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocknoderepo) EXPECT() *MocknoderepoMockRecorder {
	return m.recorder
}

// CreateMany mocks base method.
func (m *Mocknoderepo) CreateMany(ctx context.Context, nodes []domain.Node) ([]domain.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", ctx, nodes)
	ret0, _ := ret[0].([]domain.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MocknoderepoMockRecorder) CreateMany(ctx, nodes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*Mocknoderepo)(nil).CreateMany), ctx, nodes)
}

// CreateNodeInfos mocks base method.
func (m *Mocknoderepo) CreateNodeInfos(ctx context.Context, nodeInfos []domain.NodeInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeInfos", ctx, nodeInfos)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNodeInfos indicates an expected call of CreateNodeInfos.
func (mr *MocknoderepoMockRecorder) CreateNodeInfos(ctx, nodeInfos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeInfos", reflect.TypeOf((*Mocknoderepo)(nil).CreateNodeInfos), ctx, nodeInfos)
}

// GetTopology mocks base method.
func (m *Mocknoderepo) GetTopology(ctx context.Context, logID int64) (domain.Topology, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopology", ctx, logID)
	ret0, _ := ret[0].(domain.Topology)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopology indicates an expected call of GetTopology.
func (mr *MocknoderepoMockRecorder) GetTopology(ctx, logID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopology", reflect.TypeOf((*Mocknoderepo)(nil).GetTopology), ctx, logID)
}

// Mockportrepo is a mock of portrepo interface.
type Mockportrepo struct {
	ctrl     *gomock.Controller
	recorder *MockportrepoMockRecorder
}

// MockportrepoMockRecorder is the mock recorder for Mockportrepo.
type MockportrepoMockRecorder struct {
	mock *Mockportrepo
}

// NewMockportrepo creates a new mock instance.
func NewMockportrepo(ctrl *gomock.Controller) *Mockportrepo {
	mock := &Mockportrepo{ctrl: ctrl}
	mock.recorder = &MockportrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockportrepo) EXPECT() *MockportrepoMockRecorder {
	return m.recorder
}

// CreateMany mocks base method.
func (m *Mockportrepo) CreateMany(ctx context.Context, ports []domain.Port) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMany", ctx, ports)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMany indicates an expected call of CreateMany.
func (mr *MockportrepoMockRecorder) CreateMany(ctx, ports interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMany", reflect.TypeOf((*Mockportrepo)(nil).CreateMany), ctx, ports)
}

// Mocklogparser is a mock of logparser interface.
type Mocklogparser struct {
	ctrl     *gomock.Controller
	recorder *MocklogparserMockRecorder
}

// MocklogparserMockRecorder is the mock recorder for Mocklogparser.
type MocklogparserMockRecorder struct {
	mock *Mocklogparser
}

// NewMocklogparser creates a new mock instance.
func NewMocklogparser(ctrl *gomock.Controller) *Mocklogparser {
	mock := &Mocklogparser{ctrl: ctrl}
	mock.recorder = &MocklogparserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogparser) EXPECT() *MocklogparserMockRecorder {
	return m.recorder
}

// ParseArchive mocks base method.
func (m *Mocklogparser) ParseArchive(path string) (domain.ParsedLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseArchive", path)
	ret0, _ := ret[0].(domain.ParsedLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseArchive indicates an expected call of ParseArchive.
func (mr *MocklogparserMockRecorder) ParseArchive(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseArchive", reflect.TypeOf((*Mocklogparser)(nil).ParseArchive), path)
}

// Mocktxmanager is a mock of txmanager interface.
type Mocktxmanager struct {
	ctrl     *gomock.Controller
	recorder *MocktxmanagerMockRecorder
}

// MocktxmanagerMockRecorder is the mock recorder for Mocktxmanager.
type MocktxmanagerMockRecorder struct {
	mock *Mocktxmanager
}

// NewMocktxmanager creates a new mock instance.
func NewMocktxmanager(ctrl *gomock.Controller) *Mocktxmanager {
	mock := &Mocktxmanager{ctrl: ctrl}
	mock.recorder = &MocktxmanagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktxmanager) EXPECT() *MocktxmanagerMockRecorder {
	return m.recorder
}

// InTransaction mocks base method.
func (m *Mocktxmanager) InTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MocktxmanagerMockRecorder) InTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*Mocktxmanager)(nil).InTransaction), ctx, fn)
}

// Mockclock is a mock of clock interface.
type Mockclock struct {
	ctrl     *gomock.Controller
	recorder *MockclockMockRecorder
}

// MockclockMockRecorder is the mock recorder for Mockclock.
type MockclockMockRecorder struct {
	mock *Mockclock
}

// NewMockclock creates a new mock instance.
func NewMockclock(ctrl *gomock.Controller) *Mockclock {
	mock := &Mockclock{ctrl: ctrl}
	mock.recorder = &MockclockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclock) EXPECT() *MockclockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *Mockclock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockclockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*Mockclock)(nil).Now))
}
