// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package node_test is a generated GoMock package.
package node_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/befragment/yadro-test-applied-dev/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MocknodeService is a mock of nodeService interface.
type MocknodeService struct {
	ctrl     *gomock.Controller
	recorder *MocknodeServiceMockRecorder
}

// MocknodeServiceMockRecorder is the mock recorder for MocknodeService.
type MocknodeServiceMockRecorder struct {
	mock *MocknodeService
}

// NewMocknodeService creates a new mock instance.
func NewMocknodeService(ctrl *gomock.Controller) *MocknodeService {
	mock := &MocknodeService{ctrl: ctrl}
	mock.recorder = &MocknodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeService) EXPECT() *MocknodeServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocknodeService) GetByID(ctx context.Context, nodeID int) (domain.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, nodeID)
	ret0, _ := ret[0].(domain.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocknodeServiceMockRecorder) GetByID(ctx, nodeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocknodeService)(nil).GetByID), ctx, nodeID)
}

// GetNodePorts mocks base method.
func (m *MocknodeService) GetNodePorts(ctx context.Context, nodeID int) ([]domain.Port, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodePorts", ctx, nodeID)
	ret0, _ := ret[0].([]domain.Port)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodePorts indicates an expected call of GetNodePorts.
func (mr *MocknodeServiceMockRecorder) GetNodePorts(ctx, nodeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodePorts", reflect.TypeOf((*MocknodeService)(nil).GetNodePorts), ctx, nodeID)
}
